kind: pipeline
name: default

steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: build
  image: node:8
  pull: always
  commands:
  - npm install
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/repository/anis_moubarik/refworksimport
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master]
    event: [push, tag]
trigger:
  event: [push, tag]