kind: pipeline
name: default

steps:
- name: build
  image: node:8
  pull: always
  commands:
  - npm install
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/refworksimport
    registry: quay.io
    tags: [latest]
    cache_from:
      - quay.io/natlibfi/refworksimport:latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master]
    event: [push, tag]
trigger:
  event: [push, tag]