kind: pipeline
name: default

steps:
- name: build
  image: node:8
  pull: always
  commands:
  - npm install
- name: image_to_quay
  image: plugins/docker
  settings:
    repo: quay.io/anis_moubarik/refworksimport
    registry: quay.io
    tags: [latest]
    cache_from:
      - quay.io/anis_moubarik/refworksimport:latest
    username:
      from_secret: quay_robouser
    password:
      from_secret: quay_robopw
  when:
    branch: [master]
    event: [push, tag]
trigger:
  event: [push, tag]